name: "publish-technical-documentation"

on:
  pull_request:
  push:
    tags:
      - gcloud*
    paths:
      - "docs/sources/**"
  workflow_dispatch:

jobs:
  test:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out code"
        uses: "actions/checkout@v1"
      - name: "Build Website"
        run: |
          docker run -v ${PWD}/docs/sources:/hugo/content/docs/k6 --rm grafana/docs-base:latest /bin/bash -c 'make hugo'
  sync:
    runs-on: "ubuntu-latest"
    needs: "test"
    if: "github.ref == 'refs/heads/main'"
    steps:
      - uses: "actions/checkout@v1"
      - name: "Clone website-sync Action"
        # WEBSITE_SYNC_TOKEN is a fine-grained GitHub Personal Access Token that expires.
        # It must be regenerated in the grafanabot GitHub account and requires a Grafana organization
        # GitHub administrator to update the organization secret.
        # The IT helpdesk can update the organization secret.
        run: "git clone --single-branch --no-tags --depth 1 -b master https://grafanabot:${{ secrets.WEBSITE_SYNC_TOKEN }}@github.com/grafana/website-sync ./.github/actions/website-sync"

      - name: "publish-to-git"
        uses: "./.github/actions/website-sync"
        id: "publish"
        with:
          repository: "grafana/website"
          branch: "master"
          host: "github.com"
          # PUBLISH_TO_WEBSITE_TOKEN is a fine-grained GitHub Personal Access Token that expires.
          # It must be regenerated in the grafanabot GitHub account and requires a Grafana organization
          # GitHub administrator to update the organization secret.
          # The IT helpdesk can update the organization secret.
          github_pat: "grafanabot:${{ secrets.PUBLISH_TO_WEBSITE_TOKEN }}"
          source_folder: "docs/sources"
          target_folder: "content/docs/k6"
      - shell: "bash"
        run: |
          test -n "${{ steps.publish.outputs.commit_hash }}"
          test -n "${{ steps.publish.outputs.working_directory }}"
